development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dragon_development
  pool: 5
  username: root
  password: '1'

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dragon_test
  pool: 5
  username: root
  password: '1'

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dragon_production
  pool: 5
  username: root
  password: '1'
